export default {
    START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    START_UPLOAD_TASK: 'START_UPLOAD_TASK',
    REMOVE_UPLOAD_TASK: 'REMOVE_UPLOAD_TASK',
    UPDATE_UPLOAD_TASK_UPLOAD_PROGRESS: 'UPDATE_UPLOAD_TASK_UPLOAD_PROGRESS',
    CANCEL_UPLOAD_TASK: 'CANCEL_UPLOAD_TASK',
    FINISH_UPLOAD_TASK: 'FINISH_UPLOAD_TASK',

    START_LOADING_FILE_LIST: 'START_LOADING_FILE_LIST',
    FINISH_LOADING_FILE_LIST: 'FINISH_LOADING_FILE_LIST',
    SET_FILE_LIST: 'SET_FILE_LIST',
}