export default {
    // START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    SET_CURRENT_USERINFO: 'SET_CURRENT_USERINFO',

    START_UPLOAD_TASK: 'START_UPLOAD_TASK',
    RESTART_UPLOAD_TASK: 'RESTART_UPLOAD_TASK',
    REMOVE_UPLOAD_TASK: 'REMOVE_UPLOAD_TASK',
    REMOVE_UPLOADED_TASKS: 'REMOVE_UPLOADED_TASKS',
    UPDATE_UPLOAD_TASK_UPLOAD_PROGRESS: 'UPDATE_UPLOAD_TASK_UPLOAD_PROGRESS',
    CANCEL_UPLOAD_TASK: 'CANCEL_UPLOAD_TASK',
    FINISH_UPLOAD_TASK: 'FINISH_UPLOAD_TASK',

    START_LOADING_FILE_LIST: 'START_LOADING_FILE_LIST',
    SET_FILE_LIST: 'SET_FILE_LIST',
}